spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/hr?stringtype=unspecified
    username: hr
    password: 123

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: cn.cloverclc.handler
  configuration:
    map-underscore-to-camel-case: true
#    sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-enabled: true
      logic-delete-field: deleted
      logic-not-delete-value: false
      logic-delete-value: true

    type-aliases-package: cn.cloverclc.entity
logging:
  file:
    name: logs/running.log
  level:
    root: warn
    cn.cloverclc : info
server:
  port: 8080
